language: ruby
rvm:
  - 2.2.4
  - jruby-9.0.0.0
jdk:
  - openjdk7 # for jruby
before_script: export JRUBY_OPTS="--server -J-Xss1024k -J-Xmx652m -J-XX:+UseConcMarkSweepGC"
matrix:
  allow_failures:
    - rvm: rbx-2.1.1
    - rvm: ruby-head
env: RAILS_ENV=development AHN_ENV=development
notifications:
  irc: "irc.freenode.org#adhearsion"
sudo: false
